# custom params

reads: 

#humannDB: "chocophlan"

protDB_build: "uniref50_ec_filtered_diamond"

nucDB_build: "full"

cacheDir: "cacheDir"

ext: ""

resultDir: "resultDir"

humann_count_units: "cpm"

# cli params

cores: 16

use-conda: true

latency-wait: 20


#report: true