# custom params

reads: ""

mode: "paired"

#humannDB: "chocophlan"

protDB_build: "uniref50_ec_filtered_diamond"

nucDB_build: "full"

cacheDir: "cacheDir"

resultDir: "resultDir"

temp: "temp"

ext: ""

humann_count_units: "cpm"

# cli params

cores: 16

use-conda: true

latency-wait: 20

# these diamond parameters can be tweaked for better performance
dmnd_block_size: 12

dmnd_num_index_chunks: 1

# use pear to merge overlapping paired reads
merger: "bbmerge"

bowtie2_reference: ""

tools: ""

qc: "true"

trimmomatic:
  adapters: "assets/adapters/TruSeq3-PE.fa"
  max_mismatch: "2"
  pThreshold: "30"
  sThreshold: "10" 