# general
reads: "assets/test_data/input.csv"
mode: "paired"
ext: ""
help: "dummy value"
cleanup: "true"

# directory structure
results: "results"
temp: "temp"
cache: "cache"

# snakemake args
cores: 16
use-conda: true
latency-wait: 20

# tools
fastqc: "true"
merger: "bbmerge"
coretools: ""
trim: "true"

# humann args
protDB_build: "uniref50_ec_filtered_diamond"
nucDB_build: "full"
count_units: "cpm"

# diamond args, higher block size and lower idx chunks -> higher performance / mem usage
block_size: 12
num_index_chunks: 1
# report only read alignments with at least 80% identity
id_th: 80
# report alignments within the given percentage range of the top alignment score for a query 
top_range: 1

# bowtie2 args
reference: ""

# trimmomatic args
adapters_pe: "assets/adapters/TruSeq3-PE.fa"
adapters_se: "assets/adapters/TruSeq3-SE.fa"
max_mismatch: "2"
pThreshold: "30"
sThreshold: "10" 
min_adpt_len: "8"

#dga
metadata_csv: "assets/test_data/metadata.csv"
contrast_csv: "assets/test_data/contrast.csv"
formula: "cond+seed"
plot_height: 11
plot_width: 11
fc_th: 0.2
ab_th: 10
pr_th: 0.5
sig_th: 0.05