# general
reads: ""
mode: "paired"
ext: ""
help: "dummy value"

# directory structure
results: "results"
temp: "temp"
cache: "cache"

# snakemake args
cores: 16
use-conda: true
latency-wait: 20

# tools
fastqc: "true"
merger: "bbmerge"
coretools: ""
trim: "true"

# humann args
protDB_build: "uniref50_ec_filtered_diamond"
nucDB_build: "full"
count_units: "cpm"

# diamond args, higher block size and lower idx chunks -> higher performance / mem usage
block_size: 12
num_index_chunks: 1

# bowtie2 args
reference: ""

# trimmomatic args
adapters_pe: "assets/adapters/TruSeq3-PE.fa"
adapters_se: "assets/adapters/TruSeq3-SE.fa"
max_mismatch: "2"
pThreshold: "30"
sThreshold: "10" 